parameters:
#    upao_gimnasio.example.class: Upao\GimnasioBundle\Example

services:
#    upao_gimnasio.example:
#        class: %upao_gimnasio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
