parameters:
    database_driver:   pdo_sqlsrv
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     GimnasioBDE
    database_user:     sa
    database_password: .

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    secret:            ThisTokenIsNotSoSecretChangeIt
